name: Tests

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repository
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.9
            3.10
      - name: Install poetry
        run: pip install poetry

      - name: Install dev dependencies
        run: poetry install --only=dev

      - name: Run tox
        run: poetry run tox
